//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cipher.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cipher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TH 116997844
        ///HE 100689263
        ///IN 87674002
        ///ER 77134382
        ///AN 69775179
        ///RE 60923600
        ///ES 57070453
        ///ON 56915252
        ///ST 54018399
        ///NT 50701084
        ///EN 48991276
        ///AT 48274564
        ///ED 46647960
        ///ND 46194306
        ///TO 46115188
        ///OR 45725191
        ///EA 43329810
        ///TI 42888666
        ///AR 42353262
        ///TE 42295813
        ///NG 38567365
        ///AL 38211584
        ///IT 37938534
        ///AS 37773878
        ///IS 37349981
        ///HA 35971841
        ///ET 32872552
        ///SE 31532272
        ///OU 31112284
        ///OF 30540904
        ///LE 30383262
        ///SA 30080131
        ///VE 29320973
        ///RO 29230770
        ///RA 28645577
        ///RI 27634643
        ///HI 27495342
        ///NE 27331675
        ///ME 27237733
        ///DE  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string english_bigrams {
            get {
                return ResourceManager.GetString("english_bigrams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE 77534223
        ///AND 30997177
        ///ING 30679488
        ///ENT 17902107
        ///ION 17769261
        ///HER 15277018
        ///FOR 14686159
        ///THA 14222073
        ///NTH 14115952
        ///INT 13656197
        ///ERE 13287155
        ///TIO 13285065
        ///TER 12769843
        ///EST 11956466
        ///ERS 11823017
        ///ATI 11227573
        ///HAT 10900482
        ///ATE 10712298
        ///ALL 10501105
        ///ETH 10304110
        ///HES 10189449
        ///VER 10156140
        ///HIS 10051039
        ///OFT 9434246
        ///ITH 9142241
        ///FTH 9036651
        ///STH 9024058
        ///OTH 8869058
        ///RES 8835871
        ///ONT 8757161
        ///DTH 8745845
        ///ARE 8741156
        ///REA 8700830
        ///EAR 8697937
        ///WAS 8640940
        ///SIN 8629893
        ///STO 8556837
        ///TTH 8476 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string english_trigrams {
            get {
                return ResourceManager.GetString("english_trigrams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СТ 4242353
        ///ЕН 3366100
        ///ОВ 3233228
        ///НО 3215543
        ///НИ 3203049
        ///НА 3172593
        ///РА 3030046
        ///КО 2935377
        ///ТО 2730884
        ///РО 2725719
        ///АН 2692680
        ///ОС 2630218
        ///ПО 2525981
        ///ГО 2408545
        ///ЕР 2407039
        ///ОД 2303081
        ///РЕ 2279583
        ///ОР 2223739
        ///ПР 2105251
        ///ТА 2081413
        ///ВО 2045548
        ///ЕС 2000652
        ///АЛ 1956296
        ///ЛИ 1933842
        ///ОЛ 1926226
        ///ОМ 1870964
        ///ЛЕ 1838645
        ///СК 1828767
        ///ВА 1825060
        ///ЕТ 1823458
        ///ОН 1756362
        ///ОТ 1755624
        ///ТЕ 1749002
        ///НЫ 1738547
        ///ЛЬ 1720069
        ///ИН 1715210
        ///КА 1687226
        ///ИС 1687053
        ///РИ 1684163
        ///НЕ 1677891
        ///ЕЛ 1652167
        ///ТИ 1621127
        ///АС 15874 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string russian_bigrams {
            get {
                return ResourceManager.GetString("russian_bigrams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ЕНИ 1189362
        ///ОСТ 1086776
        ///ОГО 942863
        ///СТВ 831574
        ///СКО 804569
        ///СТА 772840
        ///АНИ 760630
        ///ПРО 751339
        ///ЕСТ 736955
        ///ТОР 706754
        ///ЛЬН 693146
        ///ОВА 664397
        ///НИЯ 644582
        ///НИЕ 639075
        ///ПРИ 628165
        ///ЕНН 618970
        ///ГОД 592731
        ///ОРО 581605
        ///ТЕЛ 569523
        ///СКИ 565383
        ///СТО 557991
        ///ПОЛ 552317
        ///НОВ 548646
        ///ЛЕН 543507
        ///СТИ 542427
        ///ПЕР 533137
        ///ЕГО 517926
        ///ТСЯ 510893
        ///АСТ 509803
        ///РОВ 506047
        ///СТР 491408
        ///ОЛЬ 487389
        ///ЕЛЬ 486133
        ///НОС 479373
        ///ИСТ 478089
        ///ЕРЕ 473062
        ///ПОС 460446
        ///ВАН 454626
        ///ОТО 451735
        ///НОЙ 447252
        ///ННО 446690
        ///АЛЬ 446522
        ///БЫЛ 44 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string russian_trigrams {
            get {
                return ResourceManager.GetString("russian_trigrams", resourceCulture);
            }
        }
    }
}
